from enum import Enum

SCREEN_WIDTH = 800
SCREEN_HEIGHT = SCREEN_WIDTH + 100
GRID_WIDTH = 200
GRID_HEIGHT = GRID_WIDTH
CELL_SIZE = SCREEN_WIDTH // GRID_WIDTH
GRID_LINES = GRID_WIDTH * CELL_SIZE

class CellType(Enum):
    WALL = -1
    EMPTY = 0
    RED = 1
    GREEN = 2
    BLUE = 3
    YELLOW = 4
    FOOD = 5
    LIVE = [RED, GREEN, BLUE, YELLOW]